title: OxyBoost Fitness
baseurl: /OxyBoost-Fitness # Ensure this matches your site's subdirectory
url: https://futura121.github.io # Your site's base URL
description: Getting the most out of performance breathing and exercises